### ISSUE TITLE
作成されるタグのメジャーバージョンの不具合

### ISSUE THREAD

**Issue by kimurakoki** [Songmu/tagpr#118]
## 概要
最新のタグのバージョンが`v12.13.8`だった場合、作成されるタグのバージョンが`v2.13.9`(majorバージョンの十の位が削除されてしまう)になってしまう。

**Comment by Songmu** [comment]
Oops. Thanks for the report!
I fixed it in #119 and released it as v1.0.2. Please try it.

**Comment by kimurakoki** [comment]
Thank you for your swift response !

**Comment by kimurakoki** [comment]
worked fine !
Thank you !!
