### ISSUE TITLE
[Feature Request] Add manifest.json into versionFile

### ISSUE THREAD

**Issue by ellreka** [Songmu/tagpr#125]
I want to update manifest.json version in chrome extension project.
It is probably the same as package.json.
Thanks.

**Comment by Songmu** [comment]
Thank you for the issue.

Supported at #126 and released as v1.0.4.

However, if your project already has a .tagpr configuration file in place, no additional version file detection proceeds, so set the version file by yourself as follows

```shell
git config -f .tagpr tagpr.versionFile manifest.json
```

Also note that the version number set in the file must be in semver format, such as 1.2.3.

Please try it.

**Comment by ellreka** [comment]
@Songmu 

Thank you for the quick response!
I tried it on [my project](https://github.com/ellreka/gather-auto-teleport/pull/12/files) and it worked fine.

**Comment by Songmu** [comment]
I see. You wanted to update multiple version files. I appreciate you making good use of it.
