### ISSUE TITLE
Even if `-` is specified for tagpr.versionFile, version files will be detected

### ISSUE THREAD

**Issue by toritori0318** [Songmu/tagpr#144]
Hi @Songmu.

It is written in this way in the README.
```
tagpr.versionFile

'If you do not want to use versioning files but only git tags, specify the "-" string here. '
```

I have specified `-`, but the version_file is detected.
Probably detecting files acquired [here](https://github.com/Songmu/tagpr/blob/main/tag.go#L41).

Is this the intended behavior?
Thanks.

**Comment by Songmu** [comment]
Oops. This is unintended behavior.

**Comment by toritori0318** [comment]
Thank you for the quick reply!

Perhaps stop trimming the `-` [here](https://github.com/Songmu/tagpr/blob/d930c6e9e6b5ae4e669ef04266ca3747bb01c801/config.go#L263) in stringify, and change [here](https://github.com/Songmu/tagpr/blob/d930c6e9e6b5ae4e669ef04266ca3747bb01c801/tag.go#L48) to `else if tp.cfg.VersionFile() ! = "-"`.

If it is not already supported, shall we support it?

**Comment by Songmu** [comment]
Yes, this should be supported. Since we would like to limit version file detection to only the first run.

**Comment by toritori0318** [comment]
OK, Now let's prepare the PR...

**Comment by toritori0318** [comment]
We re-ran the latest version at our service and confirmed that it works as intended! 🎉 

Thanks for a great tool!
