### ISSUE TITLE
Ability to make signed commits

### ISSUE THREAD

**Issue by tapih** [Songmu/tagpr#169]
To increase security, GitHub allows users to protect branches by accepting only signed commits.
I think it would be nice to have a option that decides if the GitHub App user signs commits or not.

As far as I know, to get it to sign commits, we need to use Commit API  instead of "git commit" ([doc](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#signature-verification-for-bots)).

**Comment by 5ouma** [comment]
@Songmu @tapih 
Has this feature already been implemented? If not, please reopen this Issue.
